### ISSUE TITLE
The regular expression used to remove forwardref methods doesn't seem to work with generic types

### ISSUE THREAD

**Issue by jimobox** [ins0mniaque/ILSupport#3]
I have wrote a method like this:
public static extern IntPtr GetPointer<T>(ref T target) where T : struct;
When building the decompiled forwardref method is not removed and "Duplicate method declaration" is thrown.
I really know nothing about how to write a regular expression but I found changing the pattern
.method [^)]+) cil ...
to
.method [^{}]+ cil ...
worked for me by try and error.

**Comment by ins0mniaque** [comment]
Thank you for reporting this.

Fixed in commit a47c9d1b247662b881dcd77a07074e75dbef7b52.
