### ISSUE TITLE
Intellisense support

### ISSUE THREAD

**Issue by floatas** [ins0mniaque/ILSupport#6]
Added support for intellisense with description. Would be nice if someone could help to test it.
 **intellisense** branch.

![intellisense](https://cloud.githubusercontent.com/assets/7883111/15788067/48cbd4b4-29ce-11e6-8b24-7dec5aa9d861.png)

**Comment by ins0mniaque** [comment]
Tested it summarily and it works well. Thanks for implementing this.

I'll look into it some more this weekend.

**Comment by ins0mniaque** [comment]
Merged into master branch on commit 7d31f8e9e0eb336ce4b135f41180b1f3e745a3c6.

Thank you again for implementing this.
