### ISSUE TITLE
Add VS2017 support

### ISSUE THREAD

**Issue by nietras** [ins0mniaque/ILSupport#8]
Please :)

**Comment by ins0mniaque** [comment]
Implemented with commit 191e74fb9dda7e629ec5a523469463ed66e25037.

I will close this issue as soon as I update the Visual Studio Gallery extension.

**Comment by ins0mniaque** [comment]
Done.

Extension is available at https://visualstudiogallery.msdn.microsoft.com/44034a7b-143d-4b51-b7bc-99aa656ba137?redir=0, and should soon be available on the marketplace at https://marketplace.visualstudio.com/items?itemName=ins0mniaque.ILSupport.
