### ISSUE TITLE
I did the 2017 IL support.

### ISSUE THREAD

**Issue by ghost** [ins0mniaque/ILSupport#9]
I updated the targets and added 4.6.2 ildasm, and the allowed versions of both Visual Studio and also the framework (4.6.2)

Also, I added uint, uint8, uint16, uint32, uint64 as keywords (they were left out, apparently).

I installed it, successfully on 2017.  It threw a minor error that says it was unsupported and that Visual Studio might be unstable, but, so far, I have seen no instability, and I use this extension a great deal for many projects.  Perhaps I forgot a minor detail?

That said, I'm not sure how you would want me to upload the end result to you?

**Comment by floatas** [comment]
Hi,
It would be best if you could create pull request.

**Comment by ins0mniaque** [comment]
Implemented with commit 191e74fb9dda7e629ec5a523469463ed66e25037.
